clientId:
  $var: $.connectorParameters.clientId
clientSecret:
  $var: $.connectorParameters.clientSecret
scopes:
  $var: $.connectorParameters.scopes
authorizeUri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
tokenUri: https://login.microsoftonline.com/common/oauth2/token
extra:
  prompt: select_account # this shows a "Select Account" screen in the OAuth flow, preventing the user from being automatically logged in with a wrong account
